### ISSUE TITLE
General obtention of the GemXP items is buggy

### ISSUE THREAD

**Issue by Seud** [marex-git/gemXp#15] opened 2013-01-26 10:05 UTC
I personnally use books as the "empty" items and enchanted books as "full" ones.
- Whenever I pick-up one of these, they are purely added to my inventory - no animation nor sound pickup,. Also, picked-up enchanted books don't always show up in my inventory until I open a chest.
- When I craft a book using shift clicking, I can only craft one at once. Worse, the ingredients are NOT consumed, yet the book is effectively created.

EDIT 2 : Without plugins, the repartition of enchantments is still uneven so it's not from the plugin. Corresponding issue removed.

**Comment by marex-git** [comment] 2013-01-26 19:16
Thanks for taking the time to report these issues; although for the future please open different issues for the different bugs. I will broke down your issue in two different ones and mark this one as wontfix. Know that I will fix them but I will refer to the new two issues.

_For the picking up action_
The reason it behave this way is because bukkit doesn't support creating new items and so to allow you to chose the number of 'gems' in a stack, the plugin handles all inventory events when it comes to gems items. For the pickup event, I cannot trigger the pick-up sound in bukkit as this sound seems relented to the event itself in the client (client side). 

With that said, while testing your issues I found the pick-up event to greedy. I will make it more specific to filled 'gems'.

_Picked-up enchanted books_
I am sorry I was unable to reproduce this one. Maybe give me more specific actions ?

_Crafting with shift_
This is a critical bug, I will look into it...

**Comment by marex-git** [comment] 2013-01-26 19:23
I just broken your issue in these two : issue #16 and #17

**Comment by marex-git** [comment] 2013-01-26 22:00
I made some fixes. if you want to test it and see if it solve your problems, please give me some feedback.
https://dl.dropbox.com/u/20943221/GemXp.jar

**Comment by marex-git** [comment] 2013-01-28 04:51
I released version 0.3.1 that includes fixes for your issues. Please update and see if it solves your problems.

**Closed as completed** 2013-01-28 04:52 UTC
Labels: wontfix
